name: Run tests on PR

on: pull_request
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@master
    
    - name: run Yamato
      run: .yamato/upm-ci-abv.yml#all_project_ci_nightly
