name: run script
on: pull_request
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@master
    
    - name: Print Pull Request Branch name extracted from GitHub context
      env:
        BRNAME: ${{ github.head_ref }}
      run: echo "Branch name = $BRNAME"
    
    - uses: actions/setup-python@v1
      with:
       python-version: '3.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
       architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REFF#refs/heads/})"
      id: extract_branch
      
    - run: python testscript.py $BRNAME
