name: Update git hooks
on: create

jobs:
  update-hook:
    runs-on: ubuntu-latest
    steps:
    - uses: srt32/git-actions@v0.0.3
      with:
        args: "git config core.hooksPath scripts\\git-hooks"
